### ISSUE TITLE
Participantes como Contribuidores

### ISSUE THREAD

**Issue by jlsilva01** [paulorsimao/HUG#1]
Ola pessoal, onde estão os demais participantes do grupo cadastrados como contribuidores?
Somente 3 até este momento.

**Comment by paulorsimao** [comment]
A princípio o pessoal deixou para começar os commits na proxima aula (terça-feira), nós 4 (O 4º Vai commitar daqui a pouco) só adiantamos algumas coisas para ter como base, o resto da equipe está trabalhando por fora com o diagrama, dicionário, etc...
