### ISSUE TITLE
Organização dos itens por pasta dentro do projeto/repositório

### ISSUE THREAD

**Issue by jlsilva01** [paulorsimao/HUG#2]
Senhores, notei a presença de vários arquivos .php no raiz do repositório.
Conforme conversamos em sala, seria importante vocês organizarem/segmentarem seus códigos por pasta.
Sugiro vocês criarem uma pasta chamada "código sistema" ou algo do tipo, para guardar os códigos PHP, e buscarem usar a mesma dinâmica para os demais itens que estão sob titulos no README.

Dúvidas, me avisem ou postem aqui.

**Comment by gmDarabas** [comment]
Feito, os arquivos php foram movidos para a pasta "sistema" e os arquivos sql movidos para pasta "sql"
