### ISSUE TITLE
Conexões e caminhos de arquivos dinâmicos

### ISSUE THREAD

**Issue by gmDarabas** [paulorsimao/HUG#4]
Algumas importações de arquivos php e algumas conexões estão sendo feitas de forma estática, é bom alterar o código para sempre considerar as variáveis de ambiente e o caminho relativo dos arquivos

**Comment by brupperuch** [comment]
Foi criado um arquivo somente com os parâmetros de conexão com o banco, porém os caminhos dos arquivos estão fixos.
