### ISSUE TITLE
Alteração da tabela historico

### ISSUE THREAD

**Issue by Arthurdelucahonorato** [paulorsimao/HUG#5]
verificar as colunas, tirar o id_apolice e o id_sinistro, virar uma só coluna para guardar todos os valores

**Comment by rubensscotti** [comment]
Foi realizado a atualização da tabela histórico. A versão final da tabela ficou da seguinte maneira: 
-- Tabela "Histórico"
CREATE TABLE historico (
  id_historico SERIAL PRIMARY KEY,
  id_imovel INT NOT NULL,
  data_atualizacao DATE NOT NULL,
  descricao VARCHAR (500) NOT NULL,
  FOREIGN KEY (id_imovel) REFERENCES imovel(id_imovel)
);
