### ISSUE TITLE
Link para o caminho dos arquivos .sql

### ISSUE THREAD

**Issue by jlsilva01** [paulorsimao/HUG#7]
O link disponível em "Scripts DDL Criação do Database:" está apontando para um diretório não atual.
Conseguem verificar/validar?

![image](https://github.com/paulorsimao/HUG/assets/484662/d6f642ca-e9d8-4e08-8f27-719b89f298b7)

**Comment by paulorsimao** [comment]
O link foi devidamente ajustado, aponta agora para uma pasta interna ao invés de um link externo.
